### ISSUE TITLE
"not granted" for app overlay on chromecast

### ISSUE THREAD

**Issue by dermarder** [virresh/matvt#12]
Hi! 
First of all thank you very much for your great work on this tool. This is really useful!

Unfortunately I have a problem: inside the app it always says "not granted" for app overlay permissions, no matter how often I try to enable or disable the settings.
The accessibility service says granted, I'm using the Chromecast with Google TV.
Any ideas?

Thanks in advance.

**Comment by virresh** [comment]
Hi @dermarder 

There are two steps:
- Grant Overlay permissions
- Enable Accessibility service

Both need to be performed in order for the mouse cursor to be visible
Is the overlay permission not being granted even after you explicitly granted it from Special App Access settings menu?

**Comment by virresh** [comment]
Has been around a year. Not sure if this is still valid. Closing it.
Please re-open if there's more information.
