### ISSUE TITLE
Doesnt work on Chromecast w/ GoogleTV as of Oct30 2021

### ISSUE THREAD

**Issue by khan95osu** [virresh/matvt#25]
just installed on CC today (CC installed today as well).  AndroidTV OS 10.  

installs ok but it wont accept permissions.  I give it access to permissions requested and googletv says it has the proper permissions... but if i click the app in the setting->app list and check permissions there, its doesnt show any.  and in the app it shows as missing all of the permissions.   manually checking permissions shows they are enabled for the app. 

i deleted and reinstalled, and got the accessibility setting to stick, but cant her the Overlay Permissions to stick. 

thus, cant get it working

**Comment by virresh** [comment]
Hi @khan95osu ,
Thanks for reporting. However, this is how special permissions work in Android TV. They are not visible on app information, but you can view them in the special permissions tab.

Can you confirm if you're able to see the applicable permissions in Special Permissions and Accessibility permissions?

This video by Tech Doctor UK should help in exact locations to check - https://youtu.be/UC7bPw2tG4c

**Comment by virresh** [comment]
Needs more information and has been quite a while now.
Closing. Please re-open if there's new information.
