### ISSUE TITLE
Port mouse to Android Phones?

### ISSUE THREAD

**Issue by virresh** [virresh/matvt#3]
Requested by Samuel (appsflipstuff@gmail.com) over email for Android phones without a touchscreen

Example model -- https://www.lg.com/us/cell-phones/lg-VN220-verizon-exalt#

Expectation -- Mouse enabled via VoiceCommand button [key 60 TV_INPUT_HDMI_1]

Since these models look like they're dumbed down version Android 6, I'm not too hopeful of them supporting most APIs
Also since it's Android 6, it'll not have support for gesture API, so we're stuck with Android getting things right via the performAction API (which IMO is highly unreliable)

**Comment by virresh** [comment]
https://github.com/virresh/matvt/releases/download/phone-v1.01/matvt-phone-app-release-v1.01.apk

Whoever is interested, here is a simple port for phones
Please use it by overriding key to whatever you wish to, default is mute key

Should work best with Android N onwards, but have added support for legacy actions (please note that these are totally unreliable and might not even work in many cases) for Android M.

**Comment by virresh** [comment]
I haven't seen this error before. My best guess would be that the drawing over other screen permission is missing.
Can you confirm if the draw over other apps permission was granted? 
Also probably you're trying the same thing, but just to confirm you've already tried the steps at https://android.stackexchange.com/a/231062 and are getting an error post that?

**Comment by lgexalter** [comment]
Yes I have granted the drawing over other apps permission successfully.
And I've also followed the steps from https://android.stackexchange.com/a/231062

**Comment by virresh** [comment]
@lgexalter unfortunately we're out of luck here.

I don't think I can do much without being able to actually see what's happening. Sorry mate. 

Leaving this issue open, just in case some developer who owns a similar device and happens to be interested in this comes across this thread.

**Comment by LGExalt** [comment]
@lgexalter what were the exact commands that you used to;
1 grant accessibility services? 
2 to start the accessibility services?
3 to start the overlay services?

thanks

**Comment by Bo-Exalt** [comment]
@LGExalt What Commands did you do to get it working?

**Comment by Bo-Exalt** [comment]
I granted overlay but when I start accessibility it says: "Requires permission android.permission.BIND_ACCESSIBILITY_SERVICE"??

**Comment by XP3R** [comment]
I tried the app on the Sonim Xp3, which is easy to allow accesibility services without adb commands, it does not have a mute button, but I was able to change that with the override setting. However I had 2 issues, one minor one that the cursor size was pretty big no matter ther size setting, but the main issue is that the select button does not click on anything, I had this problem before with other cursors, apparently the select button on the XP3  Is different than most phones. The key code is 66 and the scan code is 352. If someone can modify the code to make that select hopefully would work

**Comment by virresh** [comment]
> I successfully installed it on my exalt ;)

@LGExalt  can you elaborate a bit on the steps to install? 
IMO it'd be quite helpful for a lot of folks here
I personally don't own any such phone so it'd be great if someone can chip in to fill the gap

**Comment by virresh** [comment]
> the cursor size was pretty big no matter ther size setting
> The key code is 66 and the scan code is 352.

Thanks @XP3R for reporting, I'll update the app for phone with these modifications and update here.
@kfmdmteam has reported the ideal size for their phone is 20 x 20 pixels on community chat [1]. 
I'll adjust the cursor around these dimensions to suit your use-case

[1] https://gitter.im/virresh/community?at=605cdeab68921b62f4874241

**Comment by virresh** [comment]
Since exact commands are not shared here, I request all the folks here to please try out the following:
```
adb shell appops set io.github.virresh.matvt SYSTEM_ALERT_WINDOW allow
adb shell settings put secure enabled_accessibility_services io.github.virresh.matvt/.services.MouseEventService
adb shell settings put secure accessibility_enabled 1
```
and let me know if these work?

**Comment by XP3R** [comment]
> > the cursor size was pretty big no matter ther size setting
> > The key code is 66 and the scan code is 352.
> 
> Thanks @XP3R for reporting, I'll update the app for phone with these modifications and update here.
> @kfmdmteam has reported the ideal size for their phone is 20 x 20 pixels on community chat [1].
> I'll adjust the cursor around these dimensions to suit your use-case
> 
> [1] https://gitter.im/virresh/community?at=605cdeab68921b62f4874241

Thanks! Where can I find the updated version? (I guess I can adjust the mouse size like you posted here https://gitter.im/virresh/community?at=605cdeab68921b62f4874241 but I still would have the select button not working)

**Comment by virresh** [comment]
@XP3R I've not had the chance to update the app
I'll do it over the weekend and ping here when it's available
Hope that works

**Comment by greatjack1** [comment]
#9 Solves these issues and makes the app fully usable on LG Phones

**Comment by virresh** [comment]
Thanks a lot @greatjack1 for chipping in!

I'll do a release over the weekend along with your contributions. Thanks!

**Comment by LGExalt** [comment]
Thanks to all those who contributed to make this happen.
I'd just like to raise 2 points.
1 the cursor doesn't work in some apps. For example Waze and Uber. At first I thought it's because those apps that I was using already had a cursor added. So I tried it on a different version of Waze, which didn't have an added cursor, and it still wouldn't click on anything.

2 Once I ran the adb commands, the dedicated key to turn on voice access didn't work anymore. This may be an issue with the phone (LG Exalt). Because I had a similar issue when using button mapper. Once a enabled button mapper, I couldn't set a key for voice access.
If anyone knows of a way of fixing these issues, if really appreciate it.
Thanks

**Comment by XP3R** [comment]
> Thanks to all those who contributed to make this happen.
> I'd just like to raise 2 points.
> 1 the cursor doesn't work in some apps. For example Waze and Uber. At first I thought it's because those apps that I was using already had a cursor added. So I tried it on a different version of Waze, which didn't have an added cursor, and it still wouldn't click on anything.
> 
> 2 Once I ran the adb commands, the dedicated key to turn on voice access didn't work anymore. This may be an issue with the phone (LG Exalt). Because I had a similar issue when using button mapper. Once a enabled button mapper, I couldn't set a key for voice access.
> If anyone knows of a way of fixing these issues, I'd really appreciate it.
> Thanks

When enabling services with adb you need to put in all services you want enabled at once, so typing adb shell settings put secure enabled_accessibility_services io.github.virresh.matvt/.services.MouseEventService would turn off voice access and button mapper. You need to enable them at once separated by a colon, such as <pkg1>/<service1>:<pkg2>/<service2>

**Comment by kfmdmteam** [comment]
It won't work because matvt grabs all accessibility keys already.

**Comment by LGExalt** [comment]
> It won't work because matvt grabs all accessibility keys already. So you can't double select in accessibility what a key should do. Supposedly by the LG classic you can. But I have not tested it.

I tested it on the classic and it worked perfectly, and I was still able to set a voice access key. Not sure what the difference is. They seem to be based on the same OS.

**Comment by virresh** [comment]
> Once I ran the adb commands, the dedicated key to turn on voice access didn't work anymore.

Hmm,
Could be OS not accepting re-throws of un-used keys, but I cannot say with certainity.

matvt returns any key strokes back to the system if it cannot find a use for it.


Here's another pre-release snapshot version:
https://github.com/virresh/matvt/releases/download/phone-v1.01/matvt-phone-app-release-v1.01-snapshot.apk 

@XP3R  @LGExalt  @kfmdmteam Can you folks please test it on the various flip phones that you have for sanity?
From kfmdmteam's comment, it probably will need more modifications on LG Exalt, but I'd still be interested to know what error is thrown by adb if we don't do those modifications

This version has some rudimentary support for long touch (should work on Android 6, doesn't trigger on Android 7+)
It has a more customizable size range, so should not appear too big and have added the extra dpad down button presses, so clicking should now work

**Comment by kfmdmteam** [comment]
The vn220 is android 6 while the lg classic is android 8

**Comment by kfmdmteam** [comment]
@virresh I see this version doesn't have the options like the v1.03  would it be possable to make the phone version built in the newer one?

**Comment by virresh** [comment]
Yep, I'm working on backporting them. Asking for some early feedback so that I can incorporate more changes if required with the next major release itself :D

**Comment by kfmdmteam** [comment]
Looking great!

**Comment by virresh** [comment]
Did it work without package manipulation on the exalt phone?

**Comment by kfmdmteam** [comment]
No

**Comment by virresh** [comment]
Ah okay. Thanks for the heads up.
Can you try with this version: https://github.com/virresh/matvt/releases/download/phone-v1.01/matvt-phone-app-release-v1.01-snapshot-2.apk

It has the required package manipulation

```
adb shell appops set com.android.cts.virresh.matvt SYSTEM_ALERT_WINDOW allow
adb shell settings put secure accessibility_enabled 1
adb shell settings put secure enabled_accessibility_services com.android.cts.virresh.matvt/com.android.cts.virresh.matvt.services.MouseEventService
adb shell am startservice com.android.cts.virresh.matvt/com.android.cts.virresh.matvt.services.MouseEventService
```

**Comment by kfmdmteam** [comment]
Okay I'll try but can you set the DPI for the wording in the GUI for 10 DPI
instead of 20 DPI

**Comment by kfmdmteam** [comment]
Seems like there's an issue the package name is still not Android CTS

**Comment by virresh** [comment]
> Okay I'll try but can you set the DPI for the wording in the GUI for 10 DPI

sure

> Seems like there's an issue the package name is still not Android CTS

I've put the service in the cts package. Is there any special signing requirement also?
Did some more changes in packages, alongside dpi
https://github.com/virresh/matvt/releases/download/phone-v1.01/matvt-phone-app-release-v1.01-snapshot-3.apk

Thanks a lot for bearing with the testing

**Comment by kfmdmteam** [comment]
Can you also change the package name in the manifest?

**Comment by virresh** [comment]
Sorry about the confusion
Android Studio caching caused splits in the package
https://github.com/virresh/matvt/releases/download/phone-v1.01/matvt-phone-app-release-v1.01-snapshot-4.apk

Everything (including changes in manifest) are there in the above

**Comment by kfmdmteam** [comment]
Great I'll check it out soon. Gotta go buy a new LG classic...

**Comment by LGExalt** [comment]
> Sorry about the confusion
> Android Studio caching caused splits in the package
> https://github.com/virresh/matvt/releases/download/phone-v1.01/matvt-phone-app-release-v1.01-snapshot-4.apk
> 
> Everything (including changes in manifest) are there in the above

I got these errors.
Users\Home\Desktop\All Desktop\platform-tools>adb shell appops set com.android.cts.virresh.matvt SYSTEM_ALERT_WINDOW allow
Error: No UID for com.android.cts.virresh.matvt in user 0

C:\Users\Home\Desktop\All Desktop\platform-tools>adb shell am startservice com.android.cts.virresh.matvt/com.android.cts.virresh.matvt.services.MouseEventService
Starting service: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.android.cts.virresh.matvt/.services.MouseEventService }
Error: Not found; no service started.

**Comment by emaillk016** [comment]
it's
adb shell appops set com.android.cts.io.github.virresh.matvt SYSTEM_ALERT_WINDOW allow
adb shell settings put secure accessibility_enabled 1
adb shell settings put secure enabled_accessibility_services com.android.cts.io.github.virresh.matvt/com.android.cts.io.github.virresh.matvt.services.MouseEventService
adb shell am startservice com.android.cts.io.github.virresh.matvt/com.android.cts.io.github.virresh.matvt.services.MouseEventService

**Comment by XP3R** [comment]
I'm happy to report that the snapshot works great on the Sonim XP3, it even works on waze [some people reported it not working on waze on other phones]. The only issue I see is that in scroll mode it scrolls all the way to the bottom\top with each click. I didnt see any difference in performance between snapshot one and snapshot 4, except snapshot one had all the settings in the accessability section in addition to on the app itself, but either way is fine. It also worked with other dedicated keys for switchboard and voice access. Thanks so much!

**Comment by Bo-Exalt** [comment]
The mouse for exalt still needs modding. waze not working.

**Comment by kfmdmteam** [comment]
Just tested it on the LG classic flip,

I had some issues granting the permissions in the end I added this command
$adb shell pm grant com.android.cts.io.github.virresh.matvt
android.permission.SYSTEM_ALERT_WINDOW

And it worked great!

Just a note that on the main menu of the phone the mouse doesn't work but
it seems like it not an issue from matvt side as using the mouse from
SCRCPY also doesn't work on that menu.

So the total command I used to get it working was.

$ adb shell appops set com.android.cts.io.github.virresh.matvt
SYSTEM_ALERT_WINDOW_ALLOW

$adb shell settings put secure accessibility_enabled 1

$ adb shell settings put secure enabled_accessibility_services
com.android.cts.io.github.virresh.matvt/com.android.cts.io.github.virresh.matvt.services.MouseEventService

$ adb shell am startservice
com.android.cts.io.github.virresh.matvt/com.android.cts.io.github.virresh.matvt.services.MouseEventService

$ adb shell pm grant com.android.cts.io.github.virresh.matvt
android.permission.SYSTEM_ALERT_WINDOW

Thanks again @viresh

**Comment by virresh** [comment]
Thanks everyone for the feedback

> The mouse for exalt still needs modding

@Bo-Exalt can you explain a bit what kind of modding was required to make it work with the app you mentioned? 

> I got these errors.

Thanks @LGExalt for the errors. 
Do you still get the errors after trying commands posted by @emaillk016 ?

**Comment by Bo-Exalt** [comment]
It installs perfectly fine, just for a lot of things it doesn't click i.e. waze

**Comment by LGExalt** [comment]
Thanks @LGExalt for the errors.
> Do you still get the errors after trying commands posted by @emaillk016 ?
The commands seen to have worked. And when I open the app it says that all permissions are granted and everything is started. However I can't figure out how to enable the mouse. Pressing *** Doesn't turn it on.
(My voice access key is gone though)

**Comment by 4388450** [comment]
The only issue I see is that in scroll mode it scrolls all the way to the bottom\top with each click.

**Comment by virresh** [comment]
> It installs perfectly fine, just for a lot of things it doesn't click i.e. waze

Ah I see. I presume this to be happening on Android 6 devices. I'm a bit limited on Android 6 without root access, will see if something can be done about it.

> I can't figure out how to enable the mouse.

There's a video made by Tech Doctor UK (https://youtu.be/UC7bPw2tG4c) that explains how MATVT works on a TV. It's the same principle, just ported to phone. You can customize the key based from settings GUI based on whatever works best for your device. Let me know if you still face issues enabling it.

> scroll mode it scrolls all the way to the bottom\top with each click

Thanks, I presume this only happening on Android 7+ ?
I have a fix in mind for this issue, just didn't get enough time to address it yet. The latest version for Android TV has a scroll speed control, which should help with this problem. I'm hoping I'll get to port it to phones this weekend 🤞🏻 .

**Comment by XP3R** [comment]
> > scroll mode it scrolls all the way to the bottom\top with each click
> 
> Thanks, I presume this only happening on Android 7+ ?
> I have a fix in mind for this issue, just didn't get enough time to address it yet. The latest version for Android TV has a scroll speed control, which should help with this problem. I'm hoping I'll get to port it to phones this weekend 🤞🏻 .

I should point out its not automatically all the way to the bottom, it just scrolls A LOT but if it's a really long page it won't go all the way to the bottom. Slowing down the scroll speed a lot should help. Thanks a million!

**Comment by LGExalt** [comment]
Just realized that the activation key is set by default to holding down the star key.
I still don't have my voice access key though ☹️
And it won't click on Waze.

**Comment by virresh** [comment]
@here I've completed a port to Flipphones
The latest version is available at https://github.com/virresh/matvt/releases/tag/phone-v1.03
Apk can be downloaded from assets at the bottom of release notes.

Thanks to everyone who made this happen!
Cheers

**Comment by virresh** [comment]
Keeping in mind the above comment, I've opened seperate issues for the bugs reported as they are common for the TV and phone version. Closing this issue. Feel free to comment / re-open if required.

**Comment by Dr-Sauce** [comment]
Does anyone know how to activate it on LG Classic? I've tried holding the star(*) button; but it doesn't activate the mouse.
