### ISSUE TITLE
Airtel Xtreme box remote issue. 

### ISSUE THREAD

**Issue by sunilkcs** [virresh/matvt#33]
Hi
Can some one tell me, what is the activation key and boss key i should use in Airtel Xtreme box remote ? I have installed the application successfully and enabled all the permissions... It just the key doesnt look like working. Kindly help.

**Comment by virresh** [comment]
Hi @sunilkcs ,
I don't have an Airtel Xtreme box so I am not sure which keys would work.

Can you try setting a different boss key? If there is an info button on your remote, maybe try activating using that?
It's possible that some buttons on your remote don't actually send input to the Android operating system, and instead are handled directly by the hardware (e.g Power button). Such buttons will not work as Boss Keys.

**Comment by virresh** [comment]
Needs more information. Closing for now. If anyone has an Airtel Xtreme box and have more information / logs on this, please feel free to re-open or create a new issue and cite this one.
