### ISSUE TITLE
Clicks Work On Home Page Of Android Tv But Not In Apps 

### ISSUE THREAD

**Issue by LimitlessDonald** [virresh/matvt#38]
Hello, thanks for your awesome work on this app .
It works fine at least on the home page .
But within apps I can't click on any button .

**Comment by LimitlessDonald** [comment]
Hello @virresh  thanks for your response. Sorry I did not state my Android OS. Yes you are right , Android 11 .
I am taking a look at the link in your comment and would update my comment here

**Comment by virresh** [comment]
Cool. Closing as duplicate of #28
