### ISSUE TITLE
Ability ti scroll by mouse

### ISSUE THREAD

**Issue by pitanni** [virresh/matvt#41]
Hi,
is possible to have the ability to scroll with the mouse in an app where the DPAD does not work?

Thanks

**Comment by virresh** [comment]
Hi,
Sorry I didn't understand the query?

Scroll is supported via gesture API, so consider it like dragging a finger across the screen.
It is supposed to work at all places including ones where DPAD doesn't.
Am I missing something here?

**Comment by pitanni** [comment]
Hi,
Sorry, my mistake. 
I had disabled the bordered window.

Thank you so much for the app 👯
