### ISSUE TITLE
MaTvT-VIRRESH

### ISSUE THREAD

**Issue by darnell89** [virresh/matvt#46]
MATVT V1. 0.6.

ISSUES PROBLEMS SOLUTIONS

MATVT MOUSE FOR ATV

SUPPORT

MATVTV- MOUSE FOR ANDROID TV TOGGLE

**Comment by virresh** [comment]
Hi
Sorry I don't understand what you intended to ask / write here.
Could you clarify?

**Comment by virresh** [comment]
Closing this issue. Please open another one if required.
