### ISSUE TITLE
Not working for CHROMECAST after android 12 update.

### ISSUE THREAD

**Issue by deepujaglan** [virresh/matvt#57]
Hi , 
Many thanks for your efforts. But alas after Chromecast with Google tv got android 12 update. The mouse toggle is no longer working. Any further discussions with me  @ 9802535949 WhatsApp / j4jaglan@gmail.com

**Comment by virresh** [comment]
Duplicate of https://github.com/virresh/matvt/issues/55
Would advise you to follow that thread instead. I'll not be able to chase individual people for feedback/discussion.
